# Generated by Django 5.0.7 on 2024-11-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_create_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create',
            new_name='createdata',
        ),
    ]
